

type Props = {
  children: React.ReactNode;
};

const Button = ({ children }: Props) => {
  return <button>{children}</button>;
};

export { Button };


// Generated by CodiumAI

describe('Button', () => {

    // Renders a button element with the text content passed as children prop
    it('should render a button element with the text content passed as children prop', () => {
      const wrapper = shallow(<Button>Click me</Button>);
      expect(wrapper.find('button').text()).toEqual('Click me');
    });
});
